# Starter pipeline
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: '8DEv1AMNXczW3y4U15LL3jYf62jK93n5'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Packages\currency.converter'
    folderName: 'Currency.Converter'
    entryPoints: 'OANDA Currency Converter Flowchart.xaml'
    traceLevel: 'Information'
